version: '3.1'

services:
  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: portfolio
    ports:
      - "5432:5432"